### ISSUE TITLE
md summary and log shall follow same naming scheme as the rest of the files

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#132]

**Comment by ElliottKasoar** [comment]
The inconvenient thing for this is that the naming schemes depend on how we instantiate the MD classes.

This isn't too much of a problem for the summary, since we only create it just before `dyn.run`, but the log is currently created via `SinglePoint` so that the logs are all shared, and I'm not sure there's a particularly tidy way around that.

This would also mean we can't have the defaults in the CLI help, but that's probably fine.
