### ISSUE TITLE
we may want fine tuning as a separate option since we need to check more stuff..

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#137]
we may want fine tuning as a separate option since we need to check more stuff..
also will need a restart

_Originally posted by @alinelena in https://github.com/stfc/janus-core/pull/127#discussion_r1589959639_

**Comment by ElliottKasoar** [comment]
Should these checks not be handled by MACE's (or other MLIPs') training scripts?

We can check that `foundation_model` is passed, which triggers a few things including [`load_foundations`](https://github.com/ACEsuit/mace/blob/main/mace/tools/finetuning_utils.py#L6) from `finetuning_utils`, but otherwise would it not make more sense to contribute any more essential checks back to MACE, or are there things that would be specific to janus?

**Comment by alinelena** [comment]
for example will be useful to check that the foundation model exists, yes I agree the more fundamental stuff shall go to mace.

**Comment by ElliottKasoar** [comment]
> for example will be useful to check that the foundation model exists, yes I agree the more fundamental stuff shall go to mace.

I'm not sure there's even a straight forward way of doing that, since the model loading is done within the training script e.g.

```
if args.foundation_model is not None:
    if args.foundation_model in ["small", "medium", "large"]:
        logging.info(
            f"Using foundation model mace-mp-0 {args.foundation_model} as initial checkpoint."
        )
        calc = mace_mp(
            model=args.foundation_model,
            device=args.device,
            default_dtype=args.default_dtype,
        )
```

Even if we loaded the model, we couldn't pass it explicitly, since we have to go via the config.

We could load it and pass the path to make use of the final else [`torch.load`](https://github.com/ACEsuit/mace/blob/main/mace/cli/run_train.py#L104), but it does mean we miss any model specific logic they include.

**Comment by ElliottKasoar** [comment]
> We could load it and pass the path to make use of the final else [`torch.load`](https://github.com/ACEsuit/mace/blob/main/mace/cli/run_train.py#L104), but it does mean we miss any model-specific logic they include.

I suppose we will need to do this, or something similar, for aiida anyway though.
