### ISSUE TITLE
add pressure for geometry optimisattion

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#152]
ase allows pressure as an option for optimisation

eg to FrechetFilter we can pass scalar_pressure=...
more info in here https://wiki.fysik.dtu.dk/ase/ase/filters.html

**Comment by ElliottKasoar** [comment]
Plan is probably to an option explicitly for pressure CLI option, similar to what we have for hydrostatic strain, but it's probably worth adding a more general filter kwargs option, so anything else can be added if necessary.

**Comment by alinelena** [comment]
only if adding a filter-kwargs brings it in line with the other ones we have.

**Comment by ElliottKasoar** [comment]
I was thinking it would be via `--filter-kwargs`, similar to the existing `--opt-kwargs` option, which match the actual variables in `optimize`.

This would be different to other things that call `optimize`, since they have the extra layer of nesting e.g. `--minimize-kwargs "{'filter_kwargs': {'hydrostatic_strain' : True}}"`.

I think it's down to preference. We could unify things a bit and replace `--opt-kwargs` with a more generic `--minimize-kwargs` for `geomopt` to match other commands that use optimization, but it also makes the values more complex to write.
