### ISSUE TITLE
disable docs deployments for non main branch and forks

### ISSUE THREAD

**Issue by alinelena** [stfc/janus-core#72]

**Comment by ElliottKasoar** [comment]
It should already only be for main, shouldn't it? https://github.com/stfc/janus-core/blob/main/.github/workflows/docs.yml#L5

It also doesn't generally deploy on forks since you need to set up Pages first.

It does build the docs via the CI, but that checks they build correctly, it doesn't actually deploy.

**Comment by alinelena** [comment]
not really check my fork and you will see it fails. which is annoying. anyhow this is not priority at the moment.

**Comment by ElliottKasoar** [comment]
It is only running on main on your fork from what I can see, but yes I see what you mean - it fails because Pages isn't set up (so it doesn't actually deploy), but it does try, which is not ideal (although useful for testing, still not worth it).

For now you can disable that workflow, but yeah should be a one-line fix I'll add at some point
